export const mvpInstalledTreePaths = [
  "project.yaml",
  "roots/rules.md",
  "roots/protected-boundaries.md",
  "roots/validation.yaml",
  "roots/authority.md",
  "roots/docs.yaml",
  "why-greenhouse-spec/README.md",
  "why-greenhouse-spec/tree-structure.md",
  "why-greenhouse-spec/agent-workflow.md",
  "grown/repo-map.yaml",
  "grown/command-index.yaml",
  "grown/docs-index.yaml",
  "grown/risk-index.yaml",
  "grown/agent-index.yaml",
  "grown/evidence-index.yaml",
  "grown/failure-signatures.yaml",
  "grown/memory-index.yaml",
  "grown/skill-index.yaml",
  "grown/last-inspection.md",
  "context/manifest.yaml",
  "memory/README.md",
  "skills/README.md",
  "scripts/check-changed.mjs",
  "scripts/check-greenhouse.mjs",
  "scripts/validate-scope.mjs",
  "templates/evidence.md",
  "templates/verification.md",
] as const;

export type MvpInstalledTreePath = (typeof mvpInstalledTreePaths)[number];

export const mvpInstalledDirectories = [
  "roots",
  "why-greenhouse-spec",
  "grown",
  "context",
  "memory",
  "memory/decisions",
  "memory/lessons",
  "memory/playbooks",
  "memory/references",
  "memory/projects",
  "memory/inbox",
  "skills",
  "skills/adopted",
  "skills/drafts",
  "scripts",
  "evidence",
  "templates",
  "reports",
  "reports/context",
  "reports/doctor",
] as const;

export type MvpInstalledDirectory = (typeof mvpInstalledDirectories)[number];
