import { existsSync } from "node:fs";
import { join } from "node:path";

import { stringify as stringifyYaml } from "yaml";

import { discoverAgentFiles } from "../discovery/agent-files.js";
import { discoverCommandIndex } from "../discovery/scripts.js";
import { discoverRepoMap } from "../discovery/repo-map.js";
import { discoverRepoShape } from "../discovery/repo-shape.js";
import { discoverRiskIndex } from "../discovery/risks.js";
import { buildEvidenceIndex } from "../evidence/evidence-index.js";
import { buildFailureSignatures } from "../evidence/failure-signatures.js";
import {
  applySafeWrites,
  type PlannedWrite,
  type SafeWriteResult,
} from "../filesystem/safe-write.js";
import { buildMemoryIndex, buildSkillIndex } from "../context/knowledge-index.js";
import { proposePackageScripts } from "../native-scripts/package-script-proposals.js";
import { buildValidationProposals } from "../proposals/build-proposals.js";

export type InspectOptions = {
  cwd: string;
  dryRun?: boolean;
};

export type InspectProposal = {
  kind: "package-script" | "repo-shape" | "validation-root";
  message: string;
  name?: string;
  command?: string;
};

export type InspectReport = {
  cwd: string;
  ok: boolean;
  dryRun: boolean;
  writes: SafeWriteResult[];
  proposals: InspectProposal[];
  validationProposals: {
    total: number;
    pending: number;
    adoptable: number;
    conflicts: number;
    applied: number;
    skipped: number;
  };
};

export function runInspect(options: InspectOptions): InspectReport {
  const grownPlan = buildGrownPlan(options.cwd);
  const results = applySafeWrites({
    cwd: options.cwd,
    dryRun: options.dryRun,
    writes: grownPlan.writes,
  });

  return {
    cwd: options.cwd,
    ok: results.every((result) => result.status !== "blocked"),
    dryRun: Boolean(options.dryRun),
    writes: results,
    proposals: buildProposals(options.cwd),
    validationProposals: summarizeValidationProposals(grownPlan.validationProposals),
  };
}

export function formatInspectReport(report: InspectReport): string {
  const lines = [
    "# Greenhouse Inspect Report",
    "",
    `Repository: ${report.cwd}`,
    `Mode: ${report.dryRun ? "dry-run" : "write"}`,
    `Status: ${report.ok ? "pass" : "blocked"}`,
    `Validation proposals: ${report.validationProposals.total} total, ${report.validationProposals.pending} pending, ${report.validationProposals.adoptable} adoptable, ${report.validationProposals.conflicts} conflicts`,
    "",
    "## Grown Files",
    "",
  ];

  for (const write of report.writes) {
    const reason = write.reason ? ` - ${write.reason}` : "";
    lines.push(`- ${write.status}: ${write.relativePath}${reason}`);
  }

  lines.push("", "## Proposals", "");

  if (report.proposals.length === 0) {
    lines.push("No root, context, or package script proposals.");
  } else {
    for (const proposal of report.proposals) {
      if (proposal.kind === "package-script") {
        lines.push(`- package.json: ${proposal.message}`);
      } else if (proposal.kind === "validation-root") {
        lines.push(`- .greenhouse/roots/validation.yaml: ${proposal.message}`);
      } else {
        lines.push(`- .greenhouse/grown/repo-shape.yaml: ${proposal.message}`);
      }
    }
  }

  lines.push("");
  return lines.join("\n");
}

function buildGrownPlan(cwd: string): {
  writes: PlannedWrite[];
  validationProposals: ReturnType<typeof buildValidationProposals>;
} {
  const repoMap = discoverRepoMap(cwd);
  const repoShape = discoverRepoShape(cwd);
  const commandIndex = discoverCommandIndex(cwd);
  const riskIndex = discoverRiskIndex(cwd);
  const validationProposals = buildValidationProposals({ cwd, repoShape });
  const now = new Date().toISOString();

  return {
    validationProposals,
    writes: [
      grownWrite("repo-map.yaml", yaml(repoMap)),
      grownWrite("repo-shape.yaml", yaml(repoShape)),
      grownWrite("command-index.yaml", yaml(commandIndex)),
      grownWrite("validation-proposals.yaml", yaml(validationProposals)),
      grownWrite("docs-index.yaml", yaml({
        schema_version: 1,
        managed_by: "greenhouse-spec",
        generated_at: now,
        docs: repoMap.docs,
      })),
      grownWrite("risk-index.yaml", yaml(riskIndex)),
      grownWrite("agent-index.yaml", yaml({
        schema_version: 1,
        managed_by: "greenhouse-spec",
        generated_at: now,
        agent_files: discoverAgentFiles(cwd),
      })),
      grownWrite("evidence-index.yaml", yaml(buildEvidenceIndex(cwd))),
      grownWrite("failure-signatures.yaml", yaml(buildFailureSignatures(cwd))),
      grownWrite("memory-index.yaml", yaml(buildMemoryIndex(cwd))),
      grownWrite("skill-index.yaml", yaml(buildSkillIndex(cwd))),
      grownWrite(
        "last-inspection.md",
        [
          "# Last Greenhouse Inspection",
          "",
          `Generated by \`greenhouse-spec inspect\` on ${now}.`,
          "",
          `Source entries: ${repoMap.source.length}`,
          `Repo shape: ${repoShape.shape.join(", ") || "unknown"}`,
          `Repo shape gaps: ${repoShape.gaps.length}`,
          `Command entries: ${commandIndex.commands.length}`,
          `Validation proposals: ${validationProposals.proposals.length}`,
          `Risk entries: ${riskIndex.risks.length}`,
          "",
        ].join("\n"),
      ),
    ],
  };
}

function summarizeValidationProposals(
  validationProposals: ReturnType<typeof buildValidationProposals>,
): InspectReport["validationProposals"] {
  return {
    total: validationProposals.proposals.length,
    pending: validationProposals.proposals.filter((proposal) => proposal.status === "pending").length,
    adoptable: validationProposals.proposals.filter((proposal) => proposal.status === "adoptable").length,
    conflicts: validationProposals.proposals.filter((proposal) => proposal.status === "conflict").length,
    applied: validationProposals.proposals.filter((proposal) => proposal.status === "applied").length,
    skipped: validationProposals.proposals.filter((proposal) => proposal.status === "skipped").length,
  };
}

function buildProposals(cwd: string): InspectProposal[] {
  const proposals: InspectProposal[] = [];

  for (const proposal of proposePackageScripts(cwd)) {
    proposals.push({
      kind: "package-script",
      message:
        proposal.status === "collision"
          ? `Keep existing "${proposal.name}" script; proposed command "${proposal.command}" conflicts with "${proposal.existingCommand}".`
          : `Add "${proposal.name}" -> "${proposal.command}".`,
      name: proposal.name,
      command: proposal.command,
    });
  }

  const riskIndex = discoverRiskIndex(cwd);
  const repoShape = discoverRepoShape(cwd);
  const validationPath = join(cwd, ".greenhouse", "roots", "validation.yaml");

  if (riskIndex.risks.length > 0 && existsSync(validationPath)) {
    proposals.push({
      kind: "validation-root",
      message:
        "Review discovered risk paths and consider adding path/risk validation rules. Authored roots were not changed.",
    });
  }

  for (const gap of repoShape.gaps) {
    proposals.push({
      kind: "repo-shape",
      message: `${gap.message}${gap.paths.length > 0 ? ` Paths: ${gap.paths.join(", ")}.` : ""}`,
    });
  }

  return proposals;
}

function grownWrite(relativePath: string, content: string): PlannedWrite {
  return {
    relativePath: `.greenhouse/grown/${relativePath}`,
    content,
    kind: "generated",
  };
}

function yaml(value: unknown): string {
  return stringifyYaml(value, {
    lineWidth: 0,
  });
}
